name: abbon_test
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  app_settings: ^5.1.1
  flutter_exit_app: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/


